#!/bin/bash
# Automated runner for websiteupdater
# This script is called by cron to check and run any due projects
# NOTE: This file is regenerated by install-cron.sh and install-launchd.sh

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Change to project directory
cd "$SCRIPT_DIR"

# Activate virtual environment and run
"$SCRIPT_DIR/.venv/bin/wu" run --due >> "$SCRIPT_DIR/data/cron.log" 2>&1
